name: action-debug

inputs:
  credentials:
    description: 'Provide credentials in username:password format to access the terminal.'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Install dependencies
      shell: bash
      run: HOMEBREW_NO_INSTALL_UPGRADE=1 brew install cloudflared ttyd

    - name: Run in background
      shell: bash
      run: |-
        ttyd -c ${{ inputs.credentials }} -p 8391 -a -W bash &
        cloudflared tunnel --url http://127.0.0.1:8391 > ../action-debug.log 2>&1 &

    - name: Wait for continue file to exist
      shell: bash
      run: |-
        while [ ! -f ../action-debug.continue ]; do sleep 5; cat ../action-debug.log; done
        rm -f ../action-debug.continue
